name: Update blog posts
on:
  schedule:
    - cron: '0 * * * *' # Every 1 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hishantik/blogpost-readme@v1
        with:
          feed_list: "https://dev.to/hishantik,https://hishantik.vercel.app"
          max_post_count: 5
          layout: table
          template: "| [$title]($url) | $date |"
