name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    #permissions:
     # contents: write
    runs-on: ubuntu-latest
    steps:
 
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          #committer_branch: metrics-renders
          #committer_message: "chore: update metrics"
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          
      - name: Favorites characters
        if: ${{ success()||failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          #committer_branch: metrics-renders
          #committer_message: "chore: update metrics"
          plugin_anilist: yes
          plugin_anilist-suffle: yes
          plugin_anilist_user: dekustik
          #plugin_anilist_medias: anime
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          #committer_branch: metrics-renders
          #committer_message: "chore: update metrics"
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata
          
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          #committer_branch: metrics-renders
          #committer_message: "chore: update metrics"
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Asia/Kolkata
      
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, star, issue, member
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }} 
          plugin_people: yes
          plugin_people_types: followers

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_notable: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages-colors: rainbow
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15
