#feel free to use my template.


name: Metrics
on:
  # Schedule hourly updates 
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main /commit
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
 
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          
      - name: Favorites characters
        if: ${{ success()||failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist-suffle: yes
          plugin_anilist_user: dekustik
          #plugin_anilist_medias: anime
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

      - name: Fortune
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.fortune.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_fortune: yes


      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata
          
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Asia/Kolkata
      
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, star, issue, member
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_people: yes
          plugin_people_types: followers

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_notable: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages-colors: rainbow
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15
          
      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_only: sponsor, maintainer, octonaut, developer, manager, deployer

      - name: Repository introduction
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.introduction.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          repo: Hishantik
          base: header
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_introduction: yes

      #- name: With worldmap
       # uses: lowlighter/metrics@latest
       # with:
       #   filename: metrics.plugin.stargazers.worldmap.svg
       #   token: ${{ secrets.METRICS_TOKEN }}
       #   base: ""
       #   output_action: gist
       #   committer_gist: ${{ secrets.GIST }}
       #   plugin_stargazers: yes
       #   plugin_stargazers_charts: no
       #   plugin_stargazers_worldmap: yes
       #   plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
       #   plugin_stargazers_worldmap_sample: 200
 
      - name: Latest tweets including attachments
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.attachments.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_user: github
          plugin_tweets_limit: 1

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_leetcode: yes
          plugin_leetcode_user: Dekustik
          plugin_leetcode_sections: solved, skills, recent

     # - name: WakaTime
     #   uses: lowlighter/metrics@latest
     #   with:
     #     filename: metrics.plugin.wakatime.svg
     #     token: NOT_NEEDED
     #     base: ""
     #     output_action: gist
     #     committer_gist: ${{ secrets.GIST }}
     #     plugin_wakatime: yes
     #     plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
     #     plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: Recent posts with descriptions and cover images
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.posts.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 2
          plugin_posts_user: sarkar_234
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes

      - name: GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          
      - name: Using chartist charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.chartist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

      - name: Gists
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_gists: yes

      - name: Sponsors introduction
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.sponsors.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_sponsors: yes
          plugin_sponsors_title: Support Me!
          #plugin_sponsors_section: goal, list, about
          plugin_sponsors_size: 30
